### ISSUE TITLE
[laurent] Principled Stateful Parsing

### ISSUE THREAD

**Issue by grammarware** [grammarware/sle16#11]
Submitted by @norswap to https://github.com/grammarware/sle16/tree/master/laurent

**Comment by anthonyanjorin** [comment]
The "artefact" provided for evaluation consists of two parts:  (1) The Autumn parsing library, and (2) the Z specification from the paper.  
1. As described in the README file, I was able to build successfully with OS X El Capitan.  Even though the README only describes how to use IntelliJ, I was able to get the examples running in a few minutes using Eclipse Neon with a plugin for Kotlin.
2. I was able to download 1.5.0 of Community Z Tools and could successfully type check the Z specification.  I also built in some errors and they were flagged as such (so the type checker is really doing something).  

In general, the "artefact" is complete and consistent with the description in the paper, so I recommend the AEC's seal of approval.

A minor comment or suggestion:  It would be cool to obtain a simple dot file for the results of parsing the examples.  This is just a few minutes of work and would greatly improve the experience (there are multiple dot viewers, both for Eclipse and standalone).

**Comment by kolovos** [comment]
I was able to build Autumn successfully using the command-line instructions. The Z spec is error free according to CZT. 

Minor comment: the links to the examples at the bottom of https://github.com/grammarware/sle16/tree/master/laurent/autumn are incorrect.

**Comment by andreamocci** [comment]
My review:

The submitted artifact consists of the parsing library enriched with examples, and the Z specification of the approach itself. 

Considering the parsing library, I was followed the instructions on the README file and was able to import the project on IntelliJ. Everything compiles fine. Being unexperienced with Kotlin, I just had no idea what to do from that point on.

This sentence on the main README file suggests a command that does not work properly:
"In the autumn directory, the use-case grammar described in the paper can be run over an example by running make run-examply (after compiling, as instructed in the README file)."
After compiling everything I got the following error:
`Error: Could not find or load main class examply.MainKt`

I found that main class from the imported IntelliJ project and was able to run the example. 

Considering the Z specification, I was able to download the community tools and the specification typechecked correctly.

I found the submitted artifact in good shape but the authors could have done a better job to illustrate how to navigate and run the examples, and in particular from the resulting project. I think there is some material that is missing from the submission: On https://github.com/grammarware/sle16/tree/master/laurent/autumn , the links to the example grammars in the "Getting Started" section are broken.

**Comment by grammarware** [comment]
The Artefact Evaluation Committee of SLE 2016 has reached the conclusion yesterday during the committee meeting that this artefact conforms to the expectations and is **approved** for inclusion as auxiliary material for the publication. However, we would like to point out that the documentation of the artefact is very unclear and sometimes outright incorrect concerning the actions we expect to undertake _after_ building of the artefact.

The build process itself works fine, even though personally I would prefer one `make` command instead of having to run several of them in exact sequence — having a dependency without explicitly encoding it in the makefile is a wrong use of the makefile. However, it remained a big mystery, what to do with the examples. The links given in the README give the 404; they would not run with `make`, giving the "Could not find..." error @andreamocci pointed out above; they would not satisfy IntelliJ right away because some of the libraries are not kotlin-friendly (e.g., `violin` and the reflection library are not valid JS JARs and so far this is a strict demand of Kotlin, as far as I know); and it took me (and @anthonyanjorin before me) a bit of time hammering Eclipse into running it. Resolving dependencies manually has not been, is not, nor will ever be a sign of good reproducibility and reusability ;)

Please make some appropriate adjustments before submitting the materials to ACM, @norswap, and enjoy your seal of approval.

**Comment by norswap** [comment]
Thanks for the reviews :)

I now see the example wasn't working because:
- I failed to include the `make build-examples` command in the README.
- I did not include code to fetch the reflection library. (My tests only passed because I didn't account for `git reset` ignoring files from `.gitignore`).

I fixed the links and applied your recommendations, providing a single `make examply` command that compiles and runs the example. All commands now automatically pull dependencies and the correct Kotlin version if necessary. I updated the documentation to reflect this.

A question: What is a JS jar? I'm only familiar with the abbreviation as JavaScript, but that doesn't seem appropriate here. Google failed to enlighten me.

Still, I'm not sure there is something wrong with the libraries. I wasn't even providing the reflection library, and both work fine on both IntelliJ and the CLI by virtue of being on the classpath.

**Comment by grammarware** [comment]
@norswap: I am not an IntelliJ IDEA expert by any stretch of the imagination, but when I tried to hammer it to work without `make build-examples`, it kept complaining that this or that jar is [not a valid JavaScript library](https://discuss.kotlinlang.org/t/java-dependencies-not-a-valid-kotlin-javascript-library/270). I was as puzzled by the error message as anyone would, but apparently it's a thing that Kotlin expects some JS files with metadata inside the jar and refuses to compile if that's not the case.

**Comment by norswap** [comment]
Kotlin has both Java and Javascript backends, so I suppose there was a mishap with the configuration. In my experience, when I import a Kotlin project it always pops a tooltip asking me to "configure Kotlin" and I can choose between Java and Javascript.

**Comment by grammarware** [comment]
If I understand correctly what is written in the discussion I linked in the previous comment, Kotlin expects **Java** projects to respect the same convention since it is really just a way to store metadata.

**Comment by norswap** [comment]
I missed the link! My understanding is that if you enable the javascript backend (the "Kotlin (javascript)" bit), you can only use jars with js-specific metadata.
