### ISSUE TITLE
[bousse] Execution Framework of The GEMOC Studio

### ISSUE THREAD

**Issue by kolovos** [grammarware/sle16#16]
Submitted by @ebousse to https://github.com/grammarware/sle16/tree/master/bousse

**Comment by ghost** [comment]
Hi all,

I seem to have trouble launching the artifact's examples. Does anyone know how to?

I followed instructions [here](https://github.com/grammarware/sle16/tree/master/bousse/examples) and downloaded a frozen GEMOC Studio provided [here](http://gemoc.org/pub/studio/sle16/). The unpacked executable file, `GemocStudio` on Ubuntu, can run successfully. Following steps 1 and 2, I imported projects under `bousse/examples/examples/java/language-workbench`. GemocStudio could not build these projects.

![error building](https://cloud.githubusercontent.com/assets/21313481/18365144/80a5b41a-75df-11e6-8010-a5f6b619de7c.jpg)
![error building 2](https://cloud.githubusercontent.com/assets/21313481/18365152/874d87b6-75df-11e6-963e-6c9873f85147.jpg)

When I tried following step 2 regardless of these errors, GemocStudio launches a new window. Following step 3, I imported projects under `bousse/examples/examples/java/modeling-workbench`. When I tried to debug the `TestArduino.launch` file, it encounters an error and then nothing happens.

![error building 3](https://cloud.githubusercontent.com/assets/21313481/18365173/9b5e89e4-75df-11e6-9b8c-ca9c827534c9.jpg)
![error building 4](https://cloud.githubusercontent.com/assets/21313481/18365301/304ad026-75e0-11e6-938b-cc64a0d7657d.jpg)

I tried these steps on both Ubuntu and Mac OS and had the same problems.

**Comment by ghost** [comment]
Adding to the previous comment, I also had trouble compiling the studio from the source code. Can anyone compile the studio successfully?

I followed instructions [here](https://github.com/grammarware/sle16/tree/master/bousse/framework-sources#compiling-the-studio). I cloned the repository, changed directory to `bousse/framework-sources`, and tried to compile the studio by executing `mvn package -Dmaven.repo.local=$PWD/localm2 -P 'ignore_CI_repositories,!use_CI_repositories'` in the terminal on Ubuntu. After 20 minutes or so, maven stops with the following errors:

```
[INFO] Adding repository file:<snipped>/bousse/framework-sources/moliz.gemoc/plugins/fr.inria.diverse.trace.gemoc.generator.xmof//../../moliz-updatesite
[ERROR] Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'Local moliz update site' from location file:<snipped>/bousse/framework-sources/moliz.gemoc/plugins/fr.inria.diverse.trace.gemoc.generator.xmof//../../moliz-updatesite: No repository found at file:<snipped>/bousse/framework-sources/moliz.gemoc/plugins/fr.inria.diverse.trace.gemoc.generator.xmof//../../moliz-updatesite. -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'Local moliz update site' from location file:<snipped>/bousse/framework-sources/moliz.gemoc/plugins/fr.inria.diverse.trace.gemoc.generator.xmof//../../moliz-updatesite
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.RuntimeException: Failed to load p2 repository with ID 'Local moliz update site' from location file:<snipped>/bousse/framework-sources/moliz.gemoc/plugins/fr.inria.diverse.trace.gemoc.generator.xmof//../../moliz-updatesite
    at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.loadMetadataRepository(TargetPlatformFactoryImpl.java:302)
    at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.gatherExternalInstallableUnits(TargetPlatformFactoryImpl.java:270)
    at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:176)
    at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:128)
    at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:1)
    at org.eclipse.tycho.p2.manager.ReactorRepositoryManagerImpl.computePreliminaryTargetPlatform(ReactorRepositoryManagerImpl.java:84)
    at org.eclipse.tycho.p2.resolver.P2DependencyResolver.computePreliminaryTargetPlatform(P2DependencyResolver.java:223)
    at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject(DefaultTychoResolver.java:109)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:95)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    ... 11 more
Caused by: org.eclipse.equinox.p2.core.ProvisionException: No repository found at file:<snipped>/bousse/framework-sources/moliz.gemoc/plugins/fr.inria.diverse.trace.gemoc.generator.xmof//../../moliz-updatesite.
    at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:395)
    at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:692)
    at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
    at org.eclipse.tycho.p2.remote.RemoteMetadataRepositoryManager.loadRepository(RemoteMetadataRepositoryManager.java:61)
    at org.eclipse.tycho.p2.remote.RemoteMetadataRepositoryManager.loadRepository(RemoteMetadataRepositoryManager.java:53)
    at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.loadMetadataRepository(TargetPlatformFactoryImpl.java:298)
    ... 22 more
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
```

I performed the same steps on Mac OS and got exactly the same error messages, except that a line number -- in `at java.lang.reflect.Method.invoke(Method.java:498)` -- changed to 483.

Does anyone know what is missing in my environment?

**Comment by ebousse** [comment]
Hello, I made the submission for this artifact. 

Thank you for the thorough and well documented review. Some aspects of the studio are unfortunately not polished right now as we tried to submit a bleeding edge version with latest features but also with a few regressions - sorry about that. Here are some answers to the problems encounters:
- Regarding the error in the language workbench, I forgot to commit some files. I have pushed the missing ones, could you try pulling my latest commits and retry importing the projects? Don't hesitate to try a "clean all" as well.
- Regarding the compilation error, I will look into it right now. I wrote the build recipe to make it easier to compile everything for reviewers, but it is still quite new and it seems something is wrong (even though it works on my laptop). Thanks for the bug report.

**Comment by ghost** [comment]
Thanks @ebousse, I can now launch the workbench.

**Comment by ghost** [comment]
Here is my review.

Well documented:
- The [readme](https://github.com/grammarware/sle16/tree/master/bousse/framework-sources) for the source code seems easy to follow. It contains steps to compile the studio and locations to find the files that implement the engines and addons presented in the paper.
- The example directory contains [instructions](https://github.com/grammarware/sle16/tree/master/bousse/examples) to quickly play with the frozen versions of the studio.
- It would be helpful to document more on how to use the working studio and how to understand the example workbenches. I ran the examples on the frozen studio and saw graphical representations of models and execution states, which was nice. However, I was unable to fully interpret these outputs -- how do they correspond to the example code? The studio has generated thousands of states already -- when should I stop it?

Consistent:
- The frozen version seems to work, which should be sufficient to support that the authors build the studio presented in the paper.
- The source code seems to cover major execution engines and addons presented in the paper.
- I am unsure about the functionalities provided by the studio. With the lack of documentation, it was difficult to guess where to click on, where to look at, and how the windows correspond to contents in the paper. That said, I do believe that the authors have built a working artifact. More documentations might make a big difference.

Complete:
- The artifact contains source code that seems to cover major components in the paper.
- The artifact contains two xDSML examples: java and java+moccml. I am not sure what parts of the paper they correspond to. If they correspond to Section 4, then providing examples for the two other engines might be helpful for completeness.
- I could not verify that the source code was complete for compiling on my computers.

Easy to reuse:
- It is good that the authors made the implementation open-source and provided scripts for easy compilation.
- The [compilation instructions](https://github.com/grammarware/sle16/tree/master/bousse/framework-sources#compiling-the-studio) seem to fail on my computers. A quick way to walk around these complications might be to provide a virtual machine with everything set up.
- More documentation on the source code, such as descriptions of important functions and classes, might be helpful for researchers who want to extend the implementation.

**Comment by dstrueber** [comment]
Review: 

Using the given instructions, I was able to launch the "frozen" studio and play with the examples. In particular, on the language layer, I used the editors to view/edit the execution rules, and on the modeling layer, I walked through the example models in debug/execution mode. Although it is a bit hard to keep track of what's going on in detail, the tool generally works very much like I expected from reading the paper.

I was not able to compile the studio on my own. At first glance it seems as if certain folders are missing in the repository (see below). Still, since this is a tool paper, I think the capability to explore the tool from the user perspective is sufficient to establish reproducibility.

```
[INFO] skip non existing resourceDirectory [...]\ModelDebugging\trace\commons\plugins\fr.inria.diverse.trace.commons.model\src\main\resources
[INFO] skip non existing resourceDirectory [...]\ModelDebugging\trace\commons\plugins\fr.inria.diverse.trace.commons.model\src\test\resources
```

The availability of various examples is a good idea to help users of the framework understand its usage, thus contributing to its reusability in other contexts. More detailled descriptions of the examples as well as instructions on how the different features are used would help improve reusability even further.

From my understanding, the artifact is complete in the sense that all features described in the paper are actually part of the provided implementation, although only two of the four execution engines come with example scenarios. Making available additional examples would, again, improve reusability.

**Comment by vnssousa** [comment]
This artifact does what it reports.

The distribution of the guide through multiple files does not help the use and testing of this artifact. At the root README.md it should be clearer that the binaries are also available, leaving the impression that one must compile the framework to run the examples. It should also state the specific dependency to Oracle Java with the use of JavaFX, and that (as in my case) the system where the tests are run, has OpenJDK installed it will give out errors, and not run properly.

When trying to compile the framework it requires a relatively large amount of memory, and I was forced to change the parameters of Java, only to reach maven dependencies that where not accessible (org.eclipse.tycho for the fr.inria.diverse.trace.commons.model)

When the framework was running it executed correctly with no issues, loading well the example artifacts, but it lacked more explicit instructions directly in the guide on what to do with them at later stages.

**Comment by ebousse** [comment]
Thank you for the reviews. We have updated the READMEs to take into account various remarks. We have also updated the sources with upstream changes, and fixed the compilation process, which hopefully should work well now (it was tested on multiple computers on our side).

We might be able to polish our submission in the following days. Please do not hesitate to remove me as a contributor to this github repo as soon as you consider that no more modifications should be made for the artifacts archiving.

**Comment by grammarware** [comment]
The Artefact Evaluation Committee of SLE 2016 has reached the conclusion yesterday during the committee meeting that this artefact conforms to the expectations and is **approved** for inclusion as auxiliary material for the publication. However, besides the remarks you can find above about the quality of the documentation on how to build the project, we would like to point out that your artefact contains filenames that are too long to be handled by Windows. Your commits basically broke this repository for anyone working from that operating system and forced some of us to switch to OS X or Linux for artefact evaluation — not just of your artefact, but of anything else submitted but others. You may consider a slightly more friendly packaging for the final version.

Please make the appropriate adjustments before submitting the materials to ACM, @ebousse, and enjoy your seal of approval.

**Comment by dvojtise** [comment]
Hi
Actually the windows limitation occurs only when using some git implementations. 
When using jgit + egit for eclipse, the git operations works fine. (I'm under windows 7)
However, we will look if the code could be restructured with shorter folder names.
