### ISSUE TITLE
[parr] CodeBuff Smart Formatter

### ISSUE THREAD

**Issue by grammarware** [grammarware/sle16#3]
Submitted by @parrt to https://github.com/grammarware/sle16/tree/master/parr

**Comment by anthonyanjorin** [comment]
At the moment I'm unable to even run `mvn clean compile install` and keep getting the following error message:

```
[ERROR] Error executing Maven.
java.lang.NullPointerException
    at java.util.Hashtable.put(Hashtable.java:459)
    at org.codehaus.plexus.interpolation.os.OperatingSystemUtils.getSystemEnvVars(OperatingSystemUtils.java:73)
    at org.codehaus.plexus.interpolation.EnvarBasedValueSource.getEnvars(EnvarBasedValueSource.java:74)
    at org.codehaus.plexus.interpolation.EnvarBasedValueSource.<init>(EnvarBasedValueSource.java:64)
    at org.codehaus.plexus.interpolation.EnvarBasedValueSource.<init>(EnvarBasedValueSource.java:50)
    at org.apache.maven.settings.building.DefaultSettingsBuilder.interpolate(DefaultSettingsBuilder.java:226)
    at org.apache.maven.settings.building.DefaultSettingsBuilder.build(DefaultSettingsBuilder.java:104)
    at org.apache.maven.cli.configuration.SettingsXmlConfigurationProcessor.process(SettingsXmlConfigurationProcessor.java:137)
    at org.apache.maven.cli.MavenCli.configure(MavenCli.java:1017)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

I assume this is my fault and I'm trying to fix the problem.  Any help appreciated!

**Comment by anthonyanjorin** [comment]
ok, problem solved:  I just had to `sudo` mvn (but what a cryptic error message!).

**Comment by parrt** [comment]
I'm away from machine for a few hours but will check asap. I might have forgotten a resource file or something

**Comment by parrt** [comment]
Wow! Cryptic indeed. Weird that it needs sudo. Probably it was secretly installing a bunch of stuff

**Comment by anthonyanjorin** [comment]
There's a small typo in the example code for invoking the Java formatter:  `codebuff-1.5.1` should be `target/codebuff-1.5.1.jar` (this is correct for all other examples).

**Comment by anthonyanjorin** [comment]
Hmm...  So I've tried out the Java formatter on a very simple Java file and the result is always the entire file on one line (so the formatter removes all formatting).

What could I be doing wrong?  I followed the README as closely as possible (with the minor fix above).

**Comment by anthonyanjorin** [comment]
Ok - I forgot to unzip the corpus :)  (an error message for a non-existent or empty corpus would be nice I guess).

**Comment by anthonyanjorin** [comment]
My review:

The artefact provided for evaluation is CodeBuff, together with some grammars and data for training the formatter.

I followed the steps in the provided README file on OS X El Capitan and an 11' Air with 1.7 GHz and 8GB.
Compilation and installation worked as described with no problems.
I was also able to play around with the Java formatter and can confirm that it worked surprisingly well.
I executed all speed tests on my machine and got values about factor 2 slower.  Considering my machine is much weaker than what was used for the measurements, this makes sense.

In general, the "artefact" is complete and consistent with the description in the paper, so I recommend the AEC's seal of approval (Note, however, that I did not reproduce the graphs used in the paper).

Here are a few (minor) comments and suggestions for improvement:
1. There is a small typo in the example code for invoking the Java formatter:  `codebuff-1.5.1` should be `target/codebuff-1.5.1.jar`  
2. An error message (or warning) for a non-existent (or empty) corpus would be helpful.  I forgot to unzip and spent some time wondering why the formatter was just putting everything on a single line :)

**Comment by altmattr** [comment]
My review:

The artefact provided is CodeBuff, a code formatter that learns formatting rules from a corpus of example code.  Installation according to the instructions is simple and worked first time.

Running the code formatter required only tweaking of the memory available to the JVM (`-Xmx` option).  The default amount on my machine was not enough, nor was `256m` but `512m` was sufficient on all examples I ran.

I ran the code formatter for Java over a number Java source files from our "Object Oriented Programming Practices" course, as well as used those files as a training corpus, and found CodeBuff:
- did format them differently depending on the corpus on which it was trained
- worked on all files I gave it
- made some _unusual_ formatting decisions
- provided less formatting as the size of the corpus dropped below 10 files (as expected from the paper)

For the unusual formatting decisions, I could not find exemplars in the corpus but I didn't have time for an exhaustive search.  I consider the results I got to be consistent with the system described in the paper.

The artefact was evaluated on UbuntuMATE 16.04 using oracle's JVM for Java 8.  The artefact was evaluated on virtualised hardware using VirtualBox 5.1.4. The artefact is packaged wonderfully: compilation, testing and running are easily reproducible.  The artefact seems well built and a brief code review showed no red-flags.  My only caveat here is that I did not have the time to implement tests for the primary algorithm and none were provided.  

The paper presents a system that works now and that can be used as the basis of future work in machine learning for software engineering.  This is exactly what the artefact provides and thus I agree that it is complete, consistent, easy to re-use and well-documented.

**Comment by andreamocci** [comment]
My review:

The instructions to build Codebuff (the artifact) and run the scripts were of good quality, very clear to follow for me and I was able to run everything without any particular issue. All the commands worked at first try. I particularly appreciate the decision of using maven. 

In my Late 2013 Macbook Pro with 2 GHz Intel Core i7 and 16GB of RAM, with Mac OS 10.11.6 and Java 8, the speed tests run (natively) slightly slower than the results reported on the README file, as expected. The artifact is well packaged, but it was a little boring to copy-paste the commands from the artifact description in the README file / project page. The authors should have produced a couple of scripts (even a couple of 1 liners) to further automate the reproducibility of results.

I ran the artifact on some old Java projects I still had and as the other reviewers pointed out I also found it working pretty well. To the extent of my inspection, the artifact is consistent to what is presented in the paper and meets the expectations.

As a minor issue, the source code is not completely documented and there are some weird implementation issues. Most of the classes expose publicly implementation details (read: have public mutable fields, together with getter and setters sometimes). Maybe the authors are using some machine learning technique that requires some fields to be accessible publicly, but this issue seems spread to most of the classes, e.g. org.antlr.codebuff.InputDocument and kNNClassifier on the same package. kNNClassifier is also an example of classes which are documented, but most of their methods lack documentation.

This issue might impact reusability of the artifact.

**Comment by grammarware** [comment]
The Artefact Evaluation Committee of SLE 2016 has reached the conclusion yesterday during the committee meeting that this artefact conforms to the expectations and is **approved** for inclusion as auxiliary material for the publication. However, we would like to stress that the artefact presented here does not seem to be production ready with respect to documentation and public API. The committee has decided that coming short by industrial quality standards is not a problem for an academic artefact.

Feel free to make some appropriate adjustments before submitting the materials to ACM, @parrt, and enjoy your seal of approval.

> PS: I, @grammarware, have a conflict of interest with one of the authors of this submission, @jurgenvinju, so I have intentionally not participated to any extent in the assessment and discussion of this artefact, except for posting this notification, which is a purely administrative act of delivering the decision that has already been taken.

**Comment by parrt** [comment]
Is there an artifact badge or something that goes on the paper, I didn't see anything obvious in the article submission instructions. Also, does the submission of the artifact to this repository conclude my responsibilities for the artifact associated with this paper or do I need to upload it somewhere else as well? thanks!

**Comment by grammarware** [comment]
Dear Ter @parrt,
There are only two actions remaining from your side: adding the badge and attaching the artefact to the paper. Adding the badge should be done easily with LaTeX and possible through other means, I've just added [the text explaining how to do it](https://github.com/grammarware/sle16/blob/master/Badge.md). Attaching the artefact to the paper will be done through ACM means, you basically make a tarball/zipfile with whatever you want to go in there (including the documentation) and add it as "auxiliary material" when submitting the final version of the paper. Hope this helps!

**Comment by parrt** [comment]
Thanks @grammarware!
