### ISSUE TITLE
[sibahi] Symbolic Execution of HL Transformations

### ISSUE THREAD

**Issue by grammarware** [grammarware/sle16#4]
Submitted by @ahmadsalim to https://github.com/grammarware/sle16/tree/master/sibahi

**Comment by silvalex** [comment]
This artifact was provided for the paper entitled "Symbolic Execution of High-level Transformations", and it is the implementation of a tool that allows the user to verify transformations written in high-level languages. It is written in Scala and it also requires Java for running the necessary solvers. The instructions/descriptions included with the artifact were easy to follow, and I had no problems rerunning the black-box and white-box test generators described in the evaluation section of the paper. The results were consistent with those shown in table 1 of the paper, both in terms of time and branch coverage. While I did not create my own program, I did run the evaluator on one of the example programs provided, and the verification of that example also seemed to run as expected. In my opinion this artifact was easy to use, well documented, complete, and consistent, and so I would recommend its approval.

**Comment by ghost** [comment]
Solid artifact.

Well documented: The instructions are easy to follow. I had no problem compiling TRON and running the evaluation.

Easy to reuse: The source files seem easy to reuse, with instructions on making new example programs. The given examples look illustrative and helpful for other researchers who would like to extend the project.

Complete: The artifact seems to contain the full implementation and the subject programs to reproduce results for tables 1 and 2. These contributions should be sufficient to credit this artifact. One minor complaint is that I could not find the implementations for the seven toy programs, which makes it difficult to verify the claim that "in all of these programs the white-box test generator achieved 100% code coverage beating the black-box test generator, and all under 30 seconds of execution time." This problem should be easy to solve, since the toy programs are much simpler than the selected subject programs.

Consistent: I checked the evaluation results with tables 1 and 2. They seem to be consistent with the claims that "the white-box test generator achieves better code coverage" except "worse for the Path2Petri transformation," "the test generated by black-box had high meta-model coverage," "the white-box test generator was unsurprisingly slower." The exact numbers differed, but it should be trivial due to platform differences.

For further improvement, it might be helpful for the authors to describe the relationship between example source files and the programs in appendix E. It might also be helpful to describe specifically how to implement a new example, such as how to construct a data model using `ClassDefinition` and how to construct a program using `stmtSeq`.

**Comment by ahmadsalim** [comment]
Thank you for the great feedback.

The toy examples should run as part of the test suite as well (although, they are not the only part).
If you are interested for the source code, it is in the following files: `examples/BlogPostFeedExample.scala` (objects `BlogPostFeedTimestampsExample` and `BlogPostFeedCapitaliseTitlesExample`), `examples/IntListExample.scala` (objects `IntListContainsElementExample` and `IntListHeadTailEqExample`), `examples/Class2TableExample.scala` (objects `Class2TableSimpleExample` and `Class2TableDeepMatchingExample`), and `examples/ContactBookExample.scala` (object `ContactBookExample`).

I will of course also include them in the `README` as suggested, together with a mapping to the names used in the paper. I will also try to include a useful description of our AST for future reuse and construction of examples by third parties.

**Comment by ahmadsalim** [comment]
@grammarware Do you prefer that I update the `README` in the archived version as well?

**Comment by grammarware** [comment]
@ahmadsalim: it is not about my personal preference, but yes, the final submission of your artefact as the auxiliary material of the main paper, should include some treatment of the reviewers' remarks, unless they are impossible to accommodate.

## Review:

The artefacts builds successfully, as expected, while giving some minor warnings about non-exhaustive patterns, and passes the tests successfully (only the trailing messages are shown):

```
[info] ScalaTest
[info] Run completed in 49 seconds, 24 milliseconds.
[info] Total number of tests run: 25
[info] Suites: completed 6, aborted 0
[info] Tests: succeeded 25, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Passed: Total 25, Failed 0, Errors 0, Passed 25
[success] Total time: 95 s, completed Sep 8, 2016 12:33:19 PM
```

Running it takes considerable time (hours!), but produces the expected results:

```
$ sbt run
[info] Loading project definition from /Users/zaytsev/projects/sle16/sibahi/SymexTRON/project
[info] Set current project to SymexTRON (in build file:/Users/zaytsev/projects/sle16/sibahi/SymexTRON/)
[info] Running examples.evaluation.Evaluation 
Blackbox test generator:
| Families to Persons                                                    |       2987 ms |     100.00% |     100.00% |
| Class to Relational                                                    |       3124 ms |     100.00% |      75.00% |
| Path expression to Petri net                                           |       1665 ms |     100.00% |      88.89% |
| Rename field refactoring                                               |     103113 ms |      96.55% |      60.00% |
| Rename method refactoring                                              |     143258 ms |      96.55% |      26.67% |
| Extract super-class refactoring                                        |     101470 ms |      98.28% |      12.50% |
| Replace delegation with inheritance refactoring                        |      62718 ms |     100.00% |      41.18% |
Whitebox test generator:
| Families to Persons                                                    |     102945 ms |      92.00% |     100.00% |
| Class to Relational                                                    |    3611098 ms |      94.74% |      91.67% |
| Path expression to Petri net                                           |    3605658 ms |      37.50% |      33.33% |
| Rename field refactoring                                               |     368639 ms |      70.69% |     100.00% |
| Rename method refactoring                                              |    3703059 ms |      93.10% |      80.00% |
| Extract super-class refactoring                                        |     337793 ms |      41.38% |     100.00% |
| Replace delegation with inheritance refactoring                        |    3642858 ms |      85.19% |      76.47% |
[success] Total time: 15791 s, completed Sep 9, 2016 4:56:42 AM
$ 
```

Playing with examples given is also possible and working well and quite responsive (done in a few seconds); example run:

```
$ sbt 'run-main examples.IdIterExample'
[info] Loading project definition from /Users/zaytsev/projects/sle16/sibahi/SymexTRON/project
[info] Set current project to SymexTRON (in build file:/Users/zaytsev/projects/sle16/sibahi/SymexTRON/)
[info] Running examples.IdIterExample 
------------ Blackbox test generation -----------------

digraph blackboxmem {
  stack [shape = record label = "<X> X"];

  stack:X -> {} [style = dotted];


}


digraph blackboxmem {
  stack [shape = record label = "<X> X"];
  c [label = "c : IntSet" shape = egg];
  stack:X -> {c} [style = dotted];
  c -> {} [arrowtail = diamond dir = both label = data];

}


digraph blackboxmem {
  stack [shape = record label = "<X> X"];
  c [label = "c : Int" shape = egg];
  d [label = "d : IntSet" shape = egg];
  stack:X -> {d} [style = dotted];
  d -> {c} [arrowtail = diamond dir = both label = data];

}


digraph blackboxmem {
  stack [shape = record label = "<X> X"];
  c [label = "c : Int" shape = egg];
  e [label = "e : IntSet" shape = egg];
  d [label = "d : Int" shape = egg];
  stack:X -> {e} [style = dotted];
  e -> {d;c} [arrowtail = diamond dir = both label = data];

}

-------------------------------------------------------
------------ Whitebox test generation -----------------

digraph whiteboxmem {
  stack [shape = record label = "<X> X"];

  stack:X -> {} [style = dotted];


}


digraph whiteboxmem {
  stack [shape = record label = "<X> X"];
  c [label = "c : IntSet" shape = egg];
  stack:X -> {c} [style = dotted];
  c -> {} [arrowtail = diamond dir = both label = data];

}


digraph whiteboxmem {
  stack [shape = record label = "<X> X"];
  e [label = "e : Int" shape = egg];
  c [label = "c : IntSet" shape = egg];
  d [label = "d : IntSet" shape = egg];
  stack:X -> {c;d} [style = dotted];
  c -> {e} [arrowtail = diamond dir = both label = data];
  d -> {} [arrowtail = diamond dir = both label = data];

}

Coverage: Some(100.0)
Uncovered branches: List()
Program: 1: Y := ∅;
2: 
foreach x ∈ X do
 4: Y := (x ∪ Y)
-------------------------------------------------------
[success] Total time: 4 s, completed Sep 9, 2016 8:26:50 AM
$ 
```

With the information presented above in the comments by the author, it was easy to locate all programs and replicate the results shown in the paper (modulo hardware and system differences). The instructions were easy to follow both for installation of all prerequisites and for building the actual system. For technical reasons I had to start from an almost barebones clean OS X system, so everything starting from JDK and Scala had to be installed from scratch, but it was all pretty straightforward. The artefact contains ~4kLOC of Scala code in main modules and ~400LOC of Scala code in examples, which I have [unmethodically] examined without bumping into big surprises. In general, this is a good solid artefact that goes well with the paper, showcases its contributions and enables its future reuse and replication.

**Comment by grammarware** [comment]
The Artefact Evaluation Committee of SLE 2016 has reached the conclusion yesterday during the committee meeting that this artefact conforms to the expectations and is **approved** for inclusion as auxiliary material for the publication.

Feel free to make some appropriate adjustments before submitting the materials to ACM, @ahmadsalim, and enjoy your seal of approval.
